server:
  port: 9901

spring:
  profiles:
    active: local
  datasource:
    url: 'jdbc:h2:mem:sq-quick-start'
    username: 'sa'
    password: ''

springdoc:
  swagger-ui:
    disable-swagger-default-url: true